doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            SharedKernel:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Configuration/Doctrine/Mappings/SharedKernel'
                prefix: App\Component\SharedKernel\Domain\Entity
            Building:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Configuration/Doctrine/Mappings/Building'
                prefix: App\Component\Building\Domain\Entity
            Resource:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Configuration/Doctrine/Mappings/Resource'
                prefix: App\Component\Resource\Domain\Entity


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
